fix: Prevent warnings from missing git executable
Prevent the following error message which was shown on every run:

> Error: (file-missing "Searching for program" "No such file or directory" "git")